/**
 * Created by Administrator on 2017/8/4.
 */

/**
 * action type
 */

// export const CHANGE_BACK_STATUS = 'CHANGE_BACK_STATUS'
//
// export const CHANGE_FILTER_STATUS = 'CHANGE_FILTER_STATUS'
//
// export const CHANGE_SIDEBAR_STATUS = 'CHANGE_SIDEBAR_STATUS'
//
// export const CHANGE_TITLE = 'CHANGE_TITLE'

export const SAVE_META_DATA = 'SAVE_META_DATA'

export const SAVE_LIST_DATA = 'SAVE_LIST_DATA'


/*
* header
* */

export const CHANGE_HEADER_LEFT_CONTENT = 'CHANGE_HEADER_LEFT_CONTENT'
export const CHANGE_HEADER_RIGHT_CONTENT = 'CHANGE_HEADER_RIGHT_CONTENT'
export const CHANGE_HEADER_TITLE = 'CHANGE_HEADER_TITLE'
export const CHANGE_HEADER_VISIBLE = 'CHANGE_HEADER_VISIBLE'


